name: Build Design Tokens Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: npm ci
      - run: npm run build
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name valamisstorage --auth-mode key -d 'design-tokens' -s ./build
      - name: Trigger webhook to clear token cache
        run: |
          curl -X GET "http://2ace-85-76-107-18.ngrok.io/"
      - run: echo "🍏 This job's status is ${{ job.status }}."